### ISSUE TITLE
About evaluation on LRW

### ISSUE THREAD

**Issue by laura990501** [yuangan/evaluation_eat#2]
Nice work in Talking Head Generation!

Can u provide how to evaluate on LRW benchmark?

We would appreciate that if you could open-source the test code and dataset processing.

Thx!

**Comment by yuangan** [comment]
Thank you for your attention. The LRW data is preprocessed with our [preprocess code](https://github.com/yuangan/EAT_code#preprocessing). Due to the licensing agreement for LRW, we are unable to provide the data. You can download it from [the LRW website](https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrw1.html) and process it. As for the test code, we will make it available in our repo soon.

**Comment by laura990501** [comment]
Thank you very much for your outstanding work. 
Could you please provide an update on the evaluation code for the LRW dataset as soon as possible?

**Comment by yuangan** [comment]
Oh, sorry for late. You can refer to [here](https://github.com/yuangan/EAT_code?tab=readme-ov-file#test-lrw) for test LRW. As for the evaluation code, we will work on cleaning and releasing them this week. Thank you for your patience.

**Comment by yuangan** [comment]
Hi, we have updated the evaluation code for the LRW dataset. If you have any other questions, please feel free to contact us.

**Comment by laura990501** [comment]
Thank you very much
